
. "./qlogicae_cli_tests.ps1"
. "./about_tests.ps1"
. "./uuid4_tests.ps1"
. "./string_tests.ps1"
. "./xchacha20poly1305_tests.ps1"
. "./argon2id_tests.ps1"
. "./scripts_tests.ps1"
. "./environment_tests.ps1"
. "./windows_registry_tests.ps1"
